version: "3.9"

services:
  event-service:
    build: . # subir nuestra imagen y usarla de docker hub
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./event_service:/app/event_service
    restart: on-failure
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=event_services_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - users-postgres:/var/lib/postgresql/data
    restart: on-failure
  
  mongo: 
    image: mongo:latest
    ports: 
      - "27017:27017"
    environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
        - events-mongo:/data/db
    restart: on-failure

  reports-mongo: 
    image: mongo:latest
    ports: 
      - "27018:27017"
    environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_REPORTS_INITDB_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_REPORTS_INITDB_ROOT_PASSWORD}
        - MONGO_INITDB_DATABASE=${MONGO_REPORTS_INITDB_DATABASE}
    volumes:
        - reports-mongo:/data/db
    restart: on-failure


volumes:
  users-postgres:
  event_service:
  events-mongo:
  reports-mongo:

